### ISSUE TITLE
Stable sort

### ISSUE THREAD

**Issue by danielpanteleit** [BernhardtD/vue-sorted-table#17]
Hi,

is it possible to do a stable sort that honors previous sort operations? For example, for this table:

|c1|c2|
|---|---|
| a | 3 |
| b | 2 |
| a | 1 |
| b | 4 |

if I click on "c2" then on "c1", the table should look like this:

|c1|c2|
|---|---|
| a | 1 |
| a | 3 |
| b | 2 |
| b | 4 |

Thanks

**Comment by BernhardtD** [comment]
You should provide a custom sort function which stores previous sort requests.
The `SortedTable` component provides the property `onSort`, which should be a callback to sort the given value array. The first argument of the custom sorting function is the selected property (e.g. 'id') and the second argument is the direction ('asc' or 'desc').

You recommend taking a look to other frameworks, like [vuetify](https://vuetifyjs.com). Vuetify has a [data table component which supports multi sorting.](https://vuetifyjs.com/en/components/data-tables/#multi-sort)

**Comment by projct1** [comment]
> The `SortedTable` component provides the property `onSort`, which should be a callback to sort the given value array. The first argument of the custom sorting function is the selected property (e.g. 'id') and the second argument is the direction ('asc' or 'desc').

This is not working [image](https://user-images.githubusercontent.com/9752959/115063139-da33c700-9ef3-11eb-9b5e-fcefb0ebabc9.png) [image](https://user-images.githubusercontent.com/9752959/115063209-f172b480-9ef3-11eb-86dc-989c5a2f8d60.png)

**Comment by BernhardtD** [comment]
Your method `sorting` is defined, but does nothing.
Take a look into the [calling component](https://github.com/BernhardtD/vue-sorted-table/blob/master/src/components/SortedTable.vue#L121). The first argument of the custom sorting function is the selected property (e.g. 'id') and the second argument is the direction ('asc' or 'desc'). You should sort the array of values by your own and pass the array to the sorted table component.

This issue is related to #25

**Comment by projct1** [comment]
Thanks. But i moved to https://xaksis.github.io/vue-good-table/ and happy) Totally no pain now)
